name: .NET Core Desktop CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release] 

    runs-on: windows-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore GymApplicationV2.0.sln

    # Собираем решение 
    - name: Build the solution
      run: msbuild GymApplicationV2.0.sln /p:Configuration=${{ matrix.configuration }} /p:RestorePackages=false
